<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Models\Presence;
use App\Models\Absence;
use App\Models\Conge;
use App\Models\JourFerie; // Ajout du modèle JourFerie
use Carbon\Carbon;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\DB;

class PointageController extends Controller
{
    public function index()
    {
        $user = Auth::user();
        $today = Carbon::today();

        // Get employees who are not on approved congé for today
        $activeConges = Conge::where('approbation', 2)
            ->whereRaw('? >= date_debut', [$today->toDateString()])
            ->get()
            ->filter(function ($conge) use ($today) {
                // Calculate the congé end date, counting only weekdays
                $start = Carbon::parse($conge->date_debut);
                $numDays = $conge->num_j;
                $currentDay = 0;
                $daysCounted = 0;

                // Iterate until we count the required number of weekdays
                while ($daysCounted < $numDays) {
                    if (!$start->copy()->addDays($currentDay)->isWeekend()) {
                        $daysCounted++;
                    }
                    $currentDay++;
                }

                // The congé ends on the day before the last counted day
                $endDate = $start->copy()->addDays($currentDay - 1);
                // Check if today is within the congé period (inclusive)
                return $today->between($start, $endDate, true);
            })
            ->pluck('salarie_id')
            ->toArray();

        $projets = $user->salarie ? $user->salarie->projets()
            ->wherePivot('role', 'responsable')
            ->where('cloture', 0)
            ->with(['salaries' => function ($query) use ($activeConges) {
                $query->wherePivot('role', 'ouvrier') // Filter employees with 'ouvrier' role
                      ->where('statut', 'actif') // Filter employees with statut = actif
                      ->whereNotIn('salarie_id', $activeConges); // Exclude employees on approved congé
            }])
            ->get() : collect();

        $projets->each(function ($projet) use ($today) {
            $presences = Presence::where('id_projet', $projet->id)
                ->where('date', $today)
            ->pluck('statuts', 'salarie_id')
                ->toArray();

            $projet->salaries_data = $projet->salaries->map(function ($salarie) use ($presences) {
                return [
                    ($salarie->nom ?? '-') . ' ' . ($salarie->prenom ?? '-'),
                    $salarie->n_matricule_entreprise ?? '-',
                    $salarie->photo_url, // Use accessor
                    isset($presences[$salarie->id]) && $presences[$salarie->id] == 1,
                    $salarie->id
                ];
            })->toArray();
        });

        return view('pointage.pointage_res', compact('projets'));
    }

    public function savePresence(Request $request)
    {
        try {
            $data = $request->validate([
                'presences' => 'required|array',
                'presences.*.salarie_id' => 'required|integer|exists:salaries,id',
                'presences.*.statuts' => 'required|in:0,1',
                'presences.*.localisation' => 'nullable|string|max:255',
                'presences.*.id_projet' => 'required|integer|exists:projet,id',
            ]);

            $presences = $data['presences'];
            $today = Carbon::today();
            Log::info('Date generated by Carbon::today():', ['date' => $today->toDateString()]);
            Log::info('Presence data received:', ['presences' => $presences]);

            // Vérifier si le jour est un dimanche
            $isSunday = $today->isSunday();

            // Vérifier si le jour est un jour férié
            $isHoliday = JourFerie::where('date_debut', '<=', $today)
                ->where(function ($query) use ($today) {
                    $query->where('date_fin', '>=', $today)
                          ->orWhereNull('date_fin')
                          ->orWhere('date_fin', '=', $today);
                })
                ->exists();

            // Combiner les conditions : dimanche OU jour férié
            $restrictToChecked = $isSunday || $isHoliday;

            Log::info('Vérification du jour', [
                'date' => $today->toDateString(),
                'isSunday' => $isSunday,
                'isHoliday' => $isHoliday,
                'restrictToChecked' => $restrictToChecked,
            ]);

            // Filtrer les présences à enregistrer : uniquement statuts=1 les dimanches ou jours fériés
            $presencesToSave = $restrictToChecked
                ? array_filter($presences, fn($p) => $p['statuts'] == 1)
                : $presences;

            Log::info('Présences à enregistrer après filtrage', [
                'isSunday' => $isSunday,
                'isHoliday' => $isHoliday,
                'presencesToSave' => $presencesToSave,
                'count' => count($presencesToSave),
            ]);

            DB::beginTransaction();

            $successCount = 0;
            $errors = [];

            foreach ($presencesToSave as $presence) {
                try {
                    // Verify if the employee is an ouvrier for the project
                    $isOuvrier = DB::table('sal_projet')
                        ->where('salarie_id', $presence['salarie_id'])
                        ->where('projet_id', $presence['id_projet'])
                        ->where('role', 'ouvrier')
                        ->exists();

                    if (!$isOuvrier) {
                        throw new \Exception('L\'employé n\'est pas un ouvrier pour ce projet.');
                    }

                    // Check for existing presence record
                    $existingPresence = Presence::where('salarie_id', $presence['salarie_id'])
                        ->where('date', $today)
                        ->where('id_projet', $presence['id_projet'])
                        ->first();

                    if ($existingPresence) {
                        $existingPresence->update([
                            'mois' => $today->month,
                            'jour' => $today->day,
                            'heure' => now()->format('H:i:s'),
                            'statuts' => $presence['statuts'],
                            'localisation' => $presence['localisation'] ?? null,
                        ]);
                    } else {
                        Presence::create([
                            'salarie_id' => $presence['salarie_id'],
                            'date' => $today,
                            'id_projet' => $presence['id_projet'],
                            'mois' => $today->month,
                            'jour' => $today->day,
                            'heure' => now()->format('H:i:s'),
                            'statuts' => $presence['statuts'],
                            'localisation' => $presence['localisation'] ?? null,
                        ]);
                    }

                    Log::info('Presence record saved:', [
                        'salarie_id' => $presence['salarie_id'],
                        'id_projet' => $presence['id_projet'],
                        'statuts' => $presence['statuts'],
                    ]);

                    // Handle absences only if it's neither Sunday nor a holiday
                    if (!$restrictToChecked && $presence['statuts'] == 0) {
                        $existingAbsence = Absence::where('salarie_id', $presence['salarie_id'])
                            ->whereNull('date_fin')
                            ->first();

                        if (!$existingAbsence) {
                            Absence::create([
                                'salarie_id' => $presence['salarie_id'],
                                'date_debut' => $today,
                                'date_fin' => null,
                                'nbre_jours' => null,
                            ]);
                            Log::info('New absence recorded:', [
                                'salarie_id' => $presence['salarie_id'],
                                'date_debut' => $today->toDateString(),
                            ]);
                        }
                    } elseif ($presence['statuts'] == 1) {
                        $absences = Absence::where('salarie_id', $presence['salarie_id'])
                            ->whereNull('date_fin')
                            ->get();

                        foreach ($absences as $absence) {
                            try {
                                if (empty($absence->date_debut) || !strtotime($absence->date_debut)) {
                                    throw new \Exception("Invalid or empty absence start date.");
                                }

                                $dateDebut = Carbon::parse($absence->date_debut);
                                if ($dateDebut->gt($today)) {
                                    throw new \Exception("Absence start date is in the future.");
                                }
                                $nbreJours = $dateDebut->diffInDays($today);

                                $absence->update([
                                    'date_fin' => $today,
                                    'nbre_jours' => $nbreJours,
                                ]);

                                Log::info('Absence closed:', [
                                    'salarie_id' => $presence['salarie_id'],
                                    'date_debut' => $dateDebut->toDateString(),
                                    'date_fin' => $today->toDateString(),
                                    'nbre_jours' => $nbreJours,
                                ]);
                            } catch (\Exception $e) {
                                $errors[] = [
                                    'salarie_id' => $presence['salarie_id'],
                                    'id_projet' => $presence['id_projet'],
                                    'error' => 'Error closing absence: ' . $e->getMessage(),
                                ];
                            }
                        }
                    }

                    $successCount++;
                } catch (\Exception $e) {
                    $errors[] = [
                        'salarie_id' => $presence['salarie_id'],
                        'id_projet' => $presence['id_projet'],
                        'error' => $e->getMessage(),
                    ];
                    Log::error('Error processing presence:', [
                        'salarie_id' => $presence['salarie_id'],
                        'id_projet' => $presence['id_projet'],
                        'error' => $e->getMessage(),
                    ]);
                }
            }

            if ($restrictToChecked) {
                Log::info('Enregistrement des absences ignoré : jour est un dimanche ou un jour férié.', [
                    'date' => $today->toDateString(),
                    'isSunday' => $isSunday,
                    'isHoliday' => $isHoliday,
                ]);
            }

            DB::commit();

            return response()->json([
                'success' => $successCount > 0,
                'message' => $successCount > 0
                    ? "$successCount presence/absence records processed successfully." .
                      ($restrictToChecked ? ' (absences and unchecked presences ignored for Sunday or holiday)' : '')
                    : 'No presence or absence records processed.',
                'errors' => $errors,
            ], $successCount > 0 ? 200 : 500);
        } catch (\Illuminate\Validation\ValidationException $e) {
            Log::error('Validation error in savePresence:', [
                'errors' => $e->errors(),
                'request' => $request->all(),
            ]);
            return response()->json([
                'success' => false,
                'message' => 'Validation failed: ' . json_encode($e->errors()),
            ], 422);
        } catch (\Exception $e) {
            DB::rollBack();
            Log::error('Unexpected error in savePresence:', [
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
                'request' => $request->all(),
            ]);
            return response()->json([
                'success' => false,
                'message' => 'An error occurred: ' . $e->getMessage(),
            ], 500);
        }
    }
}